/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface change_role_Interface {
  roleId: number;
  userId: string;
}

/** 修改用户密码参数 */
export interface UpdatePasswordParams {
  /** 用户 ID */
  userId: string;
  /** 旧密码 */
  oldPassword: string;
  /** 新密码 */
  newPassword: string;
  /** 确认密码（必须和 newPassword 相同） */
  confirmPassword: string;
}

interface UpdateUserInfoParams {
  userId: string;
  username?: string;
  /** 用户的头像 可选  - 默认 */
  avatar?: string;
  /** 用户的邮箱 可选  - 默认 */
  email?: string;
  /** 用户的个性签名 可选  - 默认 */
  signature?: string;
}